// This file was auto-generated by ML.NET Model Builder. 

using System;
using MachineLearningFunML.Model;

namespace MachineLearningFunML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Home = 1F,
                SqFt = 1790F,
                Bedrooms = 2F,
                Bathrooms = 2F,
                Offers = 2F,
                Brick = false,
                Neighborhood = @"East",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"Home: {sampleData.Home}");
            Console.WriteLine($"SqFt: {sampleData.SqFt}");
            Console.WriteLine($"Bedrooms: {sampleData.Bedrooms}");
            Console.WriteLine($"Bathrooms: {sampleData.Bathrooms}");
            Console.WriteLine($"Offers: {sampleData.Offers}");
            Console.WriteLine($"Brick: {sampleData.Brick}");
            Console.WriteLine($"Neighborhood: {sampleData.Neighborhood}");
            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
