// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RobotBrainsML.Model
{
    public class ModelInput
    {
        [ColumnName("House_Price"), LoadColumn(0)]
        public float House_Price { get; set; }


        [ColumnName("Date"), LoadColumn(1)]
        public string Date { get; set; }


    }
}
