// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MachineLearningFunML.Model
{
    public class ModelInput
    {
        [ColumnName("Home"), LoadColumn(0)]
        public float Home { get; set; }


        [ColumnName("Price"), LoadColumn(1)]
        public float Price { get; set; }


        [ColumnName("SqFt"), LoadColumn(2)]
        public float SqFt { get; set; }


        [ColumnName("Bedrooms"), LoadColumn(3)]
        public float Bedrooms { get; set; }


        [ColumnName("Bathrooms"), LoadColumn(4)]
        public float Bathrooms { get; set; }


        [ColumnName("Offers"), LoadColumn(5)]
        public float Offers { get; set; }


        [ColumnName("Brick"), LoadColumn(6)]
        public bool Brick { get; set; }


        [ColumnName("Neighborhood"), LoadColumn(7)]
        public string Neighborhood { get; set; }


    }
}
